version: '3'

services:
  postgres:
    image: 'postgres:10.3-alpine'
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'
    ports:
      - 5432:5432

  mongo:
    image: mongo
    command: mongod
    ports:
    - "27017:27017"
    volumes:
    - /envdata/db
    - "$PWD/mongo_entrypoint/:/docker-entrypoint-initdb.d/"
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

  redis:
    image: 'redis:4.0-alpine'
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    volumes:
      - 'redis:/data'

  web:
    depends_on:
      - 'mongo'
      - 'redis'
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: "${UID? no UID}"
        GROUP_ID: "${GID? no GID}"
    ports:
      - '3000:3000'
    user: "${UID}:${GID}"
    tty: true
    stdin_open: true
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: "${UID? no UID}"
        GROUP_ID: "${GID? no GID}"
    command: bundle exec sidekiq
    user: "${UID}:${GID}"
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  cable:
    depends_on:
      - 'redis'
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: "${UID? no UID}"
        GROUP_ID: "${GID? no GID}"
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    user: "${UID}:${GID}"
    volumes:
      - '.:/app'
    env_file:
      - '.env'

volumes:
  mongo:
  redis:
  postgres:
