version: '2'

services:
  postgres:
    image: 'postgres:10.3-alpine'
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'
    # environment:
    #   - "POSTGRES_USER=half_tone"
    #   - "POSTGRES_PASSWORD=half_pass"
    #   - "POSTGRES_DB=${POSTGRES_DB}"
    ports:
      - 5432:5432

  redis:
    image: 'redis:4.0-alpine'
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    volumes:
      - 'redis:/data'

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  cable:
    depends_on:
      - 'redis'
    build: .
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    volumes:
      - '.:/app'
    env_file:
      - '.env'

volumes:
  redis:
  postgres:
