version: '3'

services:
  postgres:
    image: 'postgres:10.3-alpine'
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'
    ports:
      - 5432:5432

  redis:
    image: 'redis:4.0-alpine'
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    volumes:
      - 'redis:/data'

  web:
    depends_on:
      - 'postgres'
      - 'redis'
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: "${UID? no UID}"
        GROUP_ID: "${GID? no GID}"
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: "${UID? no UID}"
        GROUP_ID: "${GID? no GID}"
    command: bundle exec sidekiq
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  cable:
    depends_on:
      - 'redis'
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: "${UID? no UID}"
        GROUP_ID: "${GID? no GID}"
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    volumes:
      - '.:/app'
    env_file:
      - '.env'

volumes:
  redis:
  postgres:
